### ISSUE TITLE
安装的宝塔 在docker里面不能用计划任务

### ISSUE THREAD

**Issue by IT513** [ywfwj2008/bt-panel#1]
可以封装的时候 也把计划任务 crontab 功能也默认启动？？

![image](https://user-images.githubusercontent.com/18183932/54597700-01e4a680-4a72-11e9-9136-8f82f66720ff.png)

当前是不能用的

**Comment by IT513** [comment]
@ywfwj2008

**Comment by ywfwj2008** [comment]
可以支持计划任务的！
